// Accounts and sign-in (src/auth.ts and src/routes/account.ts, docs/contracts.md 6.6): emailed
// codes with their limits, sessions and cookies, legacy links and cookies, the auth helpers
// against Go's net/mail, and the one transaction that uses up a code and starts a session.
// Passkeys, invites, reviewers and account data are in passkeys.test.ts.
import { describe, expect, it } from 'vitest';
import { hex, utf8 } from '@colander/shared/bytes';
import { Auth, csrfOk, hashInstall, hashToken, newCode, newToken, normalizeEmail, safeNext } from '../src/auth';
import { createSession, grantRole } from '../src/store/accounts';
import { cookieOf, errorCode, expectStatus, Harness, installId, lastCode } from './api';

const MINUTE = 60_000;
const CSRF = ['X-Colander-CSRF', '1'];
const sha256hex = async (s: string) => hex(new Uint8Array(await crypto.subtle.digest('SHA-256', utf8(s))));

describe('auth helpers', () => {
	it('normalizes emails exactly as Go did with net/mail', () => {
		// Generated by running Go's NormalizeEmail over these inputs.
		const vectors: [string, string | null][] = [
			['Maya@Example.test', 'maya@example.test'],
			['  sam@colander.test ', 'sam@colander.test'],
			// Go's TrimSpace: U+0085, U+00A0 and U+3000 are space, U+FEFF is not.
			['\u0085a@b.c\u3000', 'a@b.c'],
			['\u00a0a@b.c', 'a@b.c'],
			['\ufeffa@b.c', '\ufeffa@b.c'],
			['a@b', 'a@b'],
			['a.b@c.d', 'a.b@c.d'],
			['.a@b.c', null],
			['a.@b.c', null],
			['a..b@c.d', null],
			['a@b..c', null],
			['a@.b', null],
			['a@b.', null],
			['"a"@b.c', null],
			['"a b"@b.c', null],
			['Maya <maya@example.test>', null],
			['<maya@example.test>', null],
			['maya@example.test (Maya)', null],
			['maya@example.test ()', null],
			['a b@c.d', null],
			['a@b c.d', null],
			['a@[1.2.3.4]', 'a@[1.2.3.4]'],
			['a@[1.2.3.256]', null],
			['a@[01.2.3.4]', null],
			['a@[IPv6:::1]', null],
			['a@[::1]', null],
			['a@[a]', null],
			['a@', null],
			['@b.c', null],
			['', null],
			['a', null],
			['ünï@cödé.de', 'ünï@cödé.de'],
			['ÜNÏ@CÖDÉ.DE', 'ünï@cödé.de'],
			['İ@x.y', 'i@x.y'],
			['a+tag@x.y', 'a+tag@x.y'],
			["a/b=c?d^e_f`g{h|i}j~k!#$%&'*@x.y", "a/b=c?d^e_f`g{h|i}j~k!#$%&'*@x.y"],
			['a(b)@c.d', null],
			['a,b@c.d', null],
			['a;b@c.d', null],
			['a:b@c.d', null],
			['a\\b@c.d', null],
			['a@b@c.d', null],
			['a\t@b.c', null],
			['a@b.c\n', 'a@b.c'],
			['a@b-.c', 'a@b-.c'],
			['a@-b.c', 'a@-b.c'],
			['a@b_c.d', 'a@b_c.d'],
			['a@b.c.', null],
			['a@[1.2.3.4', null],
			['a@1.2.3.4]', null],
			// At most 254 bytes.
			['a'.repeat(64) + '@' + 'b'.repeat(187) + '.c', 'a'.repeat(64) + '@' + 'b'.repeat(187) + '.c'],
			['a'.repeat(64) + '@' + 'b'.repeat(188) + '.c', null]
		];
		for (const [input, want] of vectors) expect([input, normalizeEmail(input) ?? null]).toEqual([input, want]);
	});

	it('keeps the post-sign-in redirect on this site', () => {
		expect(safeNext('/review?kind=reports')).toBe('/review?kind=reports');
		for (const bad of ['', 'review', 'https://evil.example/', '//evil.example', '/\\evil.example', '/a\r\nSet-Cookie: x', '/' + 'a'.repeat(512)]) {
			expect(safeNext(bad)).toBe('/account');
		}
		expect(safeNext('/' + 'a'.repeat(511))).toBe('/' + 'a'.repeat(511));
	});

	it('hashes tokens and install IDs and refuses malformed install IDs', async () => {
		expect(hashToken('abc')).toBe(await sha256hex('abc'));
		const id = installId(1);
		expect(id).toHaveLength(22);
		expect(hashInstall(id)).toBe(await sha256hex('colander-install:' + id));
		for (const bad of [id.slice(1), id + 'A', id.slice(0, 21) + '+', id.slice(0, 20) + '==', '']) expect(hashInstall(bad)).toBeUndefined();
	});

	it('lets reads through and wants the CSRF header and a same-origin fetch on writes', () => {
		const req = (method: string, headers: HeadersInit = {}) => new Request('https://getcolander.com/v1/account', { method, headers });
		for (const m of ['GET', 'HEAD', 'OPTIONS']) expect(csrfOk(req(m))).toBe(true);
		expect(csrfOk(req('POST'))).toBe(false);
		expect(csrfOk(req('PATCH', { 'X-Colander-CSRF': '0', 'Sec-Fetch-Site': 'same-origin' }))).toBe(false);
		// A sibling host (staging, the admin host) is same-site, not same-origin.
		expect(csrfOk(req('PATCH', { 'X-Colander-CSRF': '1', 'Sec-Fetch-Site': 'same-site' }))).toBe(false);
		expect(csrfOk(req('PATCH', { 'X-Colander-CSRF': '1' }))).toBe(false);
		expect(csrfOk(req('PATCH', { 'X-Colander-CSRF': '1', 'Sec-Fetch-Site': 'same-origin' }))).toBe(true);
	});

	it('draws 6-digit codes', () => {
		const codes = Array.from({ length: 2000 }, newCode);
		for (const c of codes) expect(c).toMatch(/^\d{6}$/);
		// Every first digit shows up: no visible bias toward low codes.
		expect(new Set(codes.map((c) => c[0])).size).toBe(10);
	});
});

/** Asks for a code; returns the flow cookie and the code the dev mail printed. */
async function askCode(h: Harness, email: string, ...headers: string[]): Promise<{ flow: string; code: string }> {
	h.mail = '';
	const res = await h.do('POST', '/v1/auth/code', { email, next: '/account' }, ...CSRF, ...headers);
	await expectStatus(res, 202);
	return { flow: cookieOf(res, 'colander_flow'), code: lastCode(h.mail) ?? '' };
}

const verify = (h: Harness, flow: string, code: string, ...headers: string[]) => h.do('POST', '/v1/auth/code/verify', { code }, ...CSRF, 'Cookie', flow, ...headers);

/** A wrong code for this one. */
const wrong = (code: string) => String((Number(code) + 1) % 1e6).padStart(6, '0');

describe('email code sign-in', () => {
	it('signs in with a 6-digit code that works once, for 10 minutes, in the browser that asked', async () => {
		const h = await Harness.create();
		await expectStatus(await h.do('GET', '/v1/account'), 401);
		const { flow, code } = await askCode(h, 'Maya@Example.test');
		expect(code).toMatch(/^\d{6}$/);
		expect(h.mail).toContain(`Subject: ${code} is your Colander sign-in code`);
		// Another browser's flow cookie, or none, never finishes it.
		const other = await askCode(h, 'someone@example.test');
		expect(await errorCode(await verify(h, other.flow, code))).toBe('code_invalid');
		expect(await errorCode(await h.do('POST', '/v1/auth/code/verify', { code }, ...CSRF))).toBe('code_expired');

		const res = await verify(h, flow, ` ${code.slice(0, 3)} ${code.slice(3)} `);
		await expectStatus(res, 200);
		const [session, cleared] = res.headers.getSetCookie();
		const value = /^colander_session=([A-Za-z0-9_-]{43});/.exec(session!)?.[1];
		// Dev mode: HttpOnly and SameSite=Strict, not Secure, no __Host- prefix.
		expect(session).toBe(`colander_session=${value}; Path=/; Max-Age=2592000; HttpOnly; SameSite=Strict`);
		expect(cleared).toBe('colander_flow=; Path=/; Max-Age=0; HttpOnly; SameSite=Strict');
		const { account } = (await res.json()) as { account: Record<string, unknown> };
		expect(account).toEqual({
			id: expect.stringMatching(/^acc_[a-z2-9]{16}$/),
			email: 'maya@example.test',
			display_name: null,
			role: 'member',
			plan: null,
			created_at: '2026-10-01T12:00:00Z',
			session: { method: 'email', authenticated_at: '2026-10-01T12:00:00Z' },
			passkey_count: 0,
			reviewer_token: null,
			requests: []
		});
		await expectStatus(await h.do('GET', '/v1/account', undefined, 'Cookie', `colander_session=${value}`), 200);
		expect(await h.run((store) => store.db.get('SELECT action, target, after, host FROM audit_log'))).toEqual({
			action: 'signed_in',
			target: account.id,
			after: 'email',
			host: 'main'
		});

		// A code works once.
		expect(await errorCode(await verify(h, flow, code))).toBe('code_expired');
		// And for 10 minutes.
		const late = await askCode(h, 'maya@example.test');
		h.clock += 10 * MINUTE + 1000;
		expect(await errorCode(await verify(h, late.flow, late.code))).toBe('code_expired');
		// Only the hash of the flow token and code is stored.
		expect(await h.run((store) => store.db.all('SELECT kind FROM auth_flows WHERE secret_hash = ?', hashToken(late.flow.split('=')[1] + late.code)))).toEqual([
			{ kind: 'email_code' }
		]);
	});

	it('always answers 202, whether or not an account exists', async () => {
		const h = await Harness.create();
		await h.signIn('maya@example.test');
		const known = await h.do('POST', '/v1/auth/code', { email: 'maya@example.test', next: '/account' }, ...CSRF);
		const unknown = await h.do('POST', '/v1/auth/code', { email: 'nobody@example.test', next: '/account' }, ...CSRF);
		expect([known.status, unknown.status]).toEqual([202, 202]);
		expect(await known.json()).toEqual(await unknown.json());
		// Asking creates no account; signing in does.
		expect(await h.run((store) => store.db.get<{ n: number }>('SELECT count(*) AS n FROM accounts')!.n)).toBe(1);
	});

	it('needs the CSRF header and a same-origin fetch to sign in, so a cross-site page cannot sign a visitor into another account', async () => {
		const h = await Harness.create();
		const { flow, code } = await askCode(h, 'attacker@example.test');
		// What an auto-submitting text/plain form sends.
		const forged = await h.do('POST', '/v1/auth/code/verify', `{"code":"${code}"}`, 'Content-Type', 'text/plain', 'Cookie', flow, 'Sec-Fetch-Site', 'cross-site');
		await expectStatus(forged, 403);
		expect(await errorCode(forged)).toBe('csrf_required');
		expect(forged.headers.get('Set-Cookie')).toBeNull();
		// A sibling host of the same site, with the header, is refused too.
		expect(await errorCode(await verify(h, flow, code, 'Sec-Fetch-Site', 'same-site'))).toBe('csrf_required');
		expect(await errorCode(await h.do('POST', '/v1/auth/code', { email: 'a@b.c', next: '/' }))).toBe('csrf_required');
		await expectStatus(await verify(h, flow, code), 200);
	});

	it('ends a code after 5 wrong tries, and pauses code sign-in for the address for 24 hours after 10 wrong codes in a day', async () => {
		const h = await Harness.create();
		let { flow, code } = await askCode(h, 'maya@example.test');
		for (let i = 1; i <= 4; i++) expect(await errorCode(await verify(h, flow, wrong(code)))).toBe('code_invalid');
		expect(await errorCode(await verify(h, flow, wrong(code)))).toBe('code_expired');
		expect(await errorCode(await verify(h, flow, code))).toBe('code_expired');

		// 5 more wrong codes across new codes use up the day's 10.
		h.clock += 60 * MINUTE;
		({ flow, code } = await askCode(h, 'maya@example.test'));
		for (let i = 1; i <= 4; i++) expect(await errorCode(await verify(h, flow, 'abc'))).toBe('code_invalid');
		h.mail = '';
		const paused = await verify(h, flow, wrong(code));
		expect(await errorCode(paused)).toBe('code_paused');
		expect(h.mail).toContain('Subject: Sign-in codes are paused for your Colander account');
		// No code goes out for 24 hours, though the answer stays 202; and none is accepted.
		const quiet = await askCode(h, 'maya@example.test');
		expect(quiet.code).toBe('');
		h.clock += 23 * 60 * MINUTE;
		const still = await askCode(h, 'maya@example.test');
		expect(still.code).toBe('');
		expect(await errorCode(await verify(h, still.flow, '000000'))).toBe('code_paused');
		// The notice went out once.
		h.clock += 2 * 60 * MINUTE;
		const back = await askCode(h, 'maya@example.test');
		expect(back.code).toMatch(/^\d{6}$/);
		await expectStatus(await verify(h, back.flow, back.code), 200);
	});

	it('limits codes to 5 an hour and 10 a day per address and 30 an hour per IP, and code tries to 30 an hour per IP', async () => {
		const h = await Harness.create();
		const ask = (email: string, ...headers: string[]) => h.do('POST', '/v1/auth/code', { email, next: '/' }, ...CSRF, ...headers);
		for (let i = 0; i < 5; i++) await expectStatus(await ask('maya@example.test'), 202);
		let res = await ask('MAYA@example.test');
		await expectStatus(res, 429);
		expect(await errorCode(res)).toBe('rate_limited');
		expect(res.headers.get('Retry-After')).toBe('720');
		expect(await h.run((store) => store.db.get<{ n: number }>('SELECT count(*) AS n FROM auth_flows')!.n)).toBe(5);
		// Over a day, 10 at most.
		for (let i = 0; i < 5; i++) {
			h.clock += 12 * MINUTE;
			await expectStatus(await ask('maya@example.test'), 202);
		}
		h.clock += 60 * MINUTE;
		await expectStatus(await ask('maya@example.test'), 429);
		h.clock += 3 * 60 * MINUTE;
		await expectStatus(await ask('maya@example.test'), 202);

		// The address quota counts every email; another address has its own.
		const fresh = await Harness.create();
		for (let i = 0; i < 30; i++) await expectStatus(await fresh.do('POST', '/v1/auth/code', { email: `user${i}@example.test`, next: '/' }, ...CSRF), 202);
		await expectStatus(await fresh.do('POST', '/v1/auth/code', { email: 'user99@example.test', next: '/' }, ...CSRF), 429);
		await expectStatus(await fresh.do('POST', '/v1/auth/code', { email: 'user99@example.test', next: '/' }, ...CSRF, 'x-colander-ip-hash', 'elsewhere'), 202);

		// 30 code tries an hour per IP, across flows.
		const tries = await Harness.create();
		const flows = [];
		for (let i = 0; i < 9; i++) flows.push(await askCode(tries, `try${i}@example.test`));
		for (let i = 0; i < 30; i++) expect((await verify(tries, flows[Math.floor(i / 4)]!.flow, 'zzzzzz')).status).toBe(400);
		await expectStatus(await verify(tries, flows[8]!.flow, flows[8]!.code), 429);
		await expectStatus(await verify(tries, flows[8]!.flow, flows[8]!.code, 'x-colander-ip-hash', 'elsewhere'), 200);
	});

	it('prints the dev mail in the block e2e/tests/stack.ts parses', async () => {
		const h = await Harness.create();
		await askCode(h, 'rae@colander.test');
		const mails = h.mail
			.split('==== Colander dev mail (not sent) ====')
			.slice(1)
			.map((block) => ({
				to: /^To: (.+)$/m.exec(block)?.[1] ?? '',
				subject: /^Subject: (.+)$/m.exec(block)?.[1] ?? '',
				body: block.split('======================================')[0]!
			}));
		expect(mails).toHaveLength(1);
		expect(mails[0]!.to).toBe('rae@colander.test');
		expect(mails[0]!.subject).toMatch(/^\d{6} is your Colander sign-in code$/);
		expect(/^ {4}(\d{6})$/m.exec(mails[0]!.body)?.[1]).toBe(mails[0]!.subject.slice(0, 6));
	});

	it('uses up the code and starts the session in one transaction', async () => {
		const h = await Harness.create();
		const { flow, code } = await askCode(h, 'maya@example.test');
		await h.run((store) => store.db.run("CREATE TRIGGER no_sessions BEFORE INSERT ON sessions BEGIN SELECT RAISE(ABORT, 'sessions are down'); END"));
		await expectStatus(await verify(h, flow, code), 500);
		// The failed session left the code usable and created no account.
		expect(
			await h.run((store) => [store.db.get<{ n: number }>('SELECT count(*) AS n FROM auth_flows')!.n, store.db.get<{ n: number }>('SELECT count(*) AS n FROM accounts')!.n])
		).toEqual([1, 0]);
		await h.run((store) => store.db.run('DROP TRIGGER no_sessions'));
		await expectStatus(await verify(h, flow, code), 200);
	});

	it('refuses bad bodies as Go decode() did', async () => {
		const h = await Harness.create();
		const cases: [unknown, number, string][] = [
			[{ email: 'not an email' }, 400, 'invalid_email'],
			[{ email: 'maya@example.test', remember: true }, 400, 'unknown_field'],
			[{ email: 5 }, 400, 'invalid_json'],
			['{"email": "maya@example.test"} {}', 400, 'invalid_json'],
			['', 400, 'invalid_json'],
			['[]', 400, 'invalid_json'],
			[{ email: 'maya@example.test', next: 'x'.repeat(9000) }, 413, 'too_large']
		];
		for (const [body, status, code] of cases) {
			const res = await h.do('POST', '/v1/auth/code', body, ...CSRF);
			await expectStatus(res, status);
			expect(await errorCode(res)).toBe(code);
		}
		// Go matches field names regardless of case, and null keeps the zero value.
		await expectStatus(await h.do('POST', '/v1/auth/code', { Email: 'maya@example.test', next: null }, ...CSRF), 202);
	});

	it('logs out, clearing the session and the cookie; outside dev cookies are __Host-, Secure and SameSite=Strict', async () => {
		const h = await Harness.create();
		const cookie = await h.signIn('maya@example.test');
		const res = await h.do('POST', '/v1/auth/logout', undefined, 'Cookie', cookie, ...CSRF);
		await expectStatus(res, 204);
		expect(res.headers.get('Set-Cookie')).toBe('colander_session=; Path=/; Max-Age=0; HttpOnly; SameSite=Strict');
		await expectStatus(await h.do('GET', '/v1/account', undefined, 'Cookie', cookie), 401);
		expect(await h.run((store) => store.db.get<{ n: number }>('SELECT count(*) AS n FROM sessions')!.n)).toBe(0);

		const prod = await h.run((store) => {
			const auth = new Auth(store.db, () => h.clock, false);
			return [auth.signOut(new Request('https://getcolander.com/')), auth.cookie(auth.names.flow, 'f', 600)];
		});
		expect(prod).toEqual(['__Host-colander_session=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict', '__Host-colander_flow=f; Path=/; Max-Age=600; HttpOnly; Secure; SameSite=Strict']);
	});

	it('still finishes sign-in links mailed before codes shipped, within their 20 minutes', async () => {
		const h = await Harness.create();
		const link = newToken();
		await h.run((store) =>
			store.db.run(
				'INSERT INTO magic_links (token_hash, email, next, created_at, expires_at) VALUES (?, ?, ?, ?, ?)',
				link.hash,
				'maya@example.test',
				'/account',
				h.s,
				h.s + 1200
			)
		);
		await expectStatus(await h.do('POST', '/v1/auth/verify', { token: link.raw }), 403);
		const res = await h.do('POST', '/v1/auth/verify', { token: link.raw }, ...CSRF);
		await expectStatus(res, 200);
		expect(((await res.json()) as { account: { session: { method: string } } }).account.session.method).toBe('email');
		expect(await errorCode(await h.do('POST', '/v1/auth/verify', { token: link.raw }, ...CSRF))).toBe('link_invalid');
		// /v1/auth/email no longer sends links.
		await expectStatus(await h.do('POST', '/v1/auth/email', { email: 'maya@example.test' }, ...CSRF), 404);
	});

	it('moves a session from before the migration to the __Host- cookie with the same token, and nothing else', async () => {
		const h = await Harness.create();
		const old = newToken();
		const fresh = newToken();
		await h.run((store) => {
			const a = grantRole(store.db, 'maya@example.test', 'member', h.s, { host: 'job' });
			createSession(store.db, { tokenHash: old.hash, accountId: a.id, method: 'email', now: h.s, expires: h.s + 3600 });
			createSession(store.db, { tokenHash: fresh.hash, accountId: a.id, method: 'email', now: h.s, expires: h.s + 3600 });
			store.db.run('UPDATE sessions SET legacy = 1 WHERE token_hash = ?', old.hash);
			// Production names for this test: the dev Store reads colander_session itself.
			(store as unknown as { auth: Auth }).auth = new Auth(store.db, () => h.clock, false);
		});
		const res = await h.do('GET', '/v1/account', undefined, 'Cookie', `colander_session=${old.raw}`);
		await expectStatus(res, 200);
		expect(res.headers.getSetCookie()).toEqual([
			`__Host-colander_session=${old.raw}; Path=/; Max-Age=3600; HttpOnly; Secure; SameSite=Strict`,
			'colander_session=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Lax'
		]);
		// A session created after the migration is never read under the old name, which any subdomain could set.
		await expectStatus(await h.do('GET', '/v1/account', undefined, 'Cookie', `colander_session=${fresh.raw}`), 401);
		// Nor is the old name read when a __Host- cookie came along.
		const both = await h.do('GET', '/v1/account', undefined, 'Cookie', `colander_session=${old.raw}; __Host-colander_session=${fresh.raw}`);
		await expectStatus(both, 200);
		expect(both.headers.getSetCookie()).toEqual([]);
	});
});

describe('account', () => {
	it('needs the CSRF header on cookie writes', async () => {
		const h = await Harness.create();
		const cookie = await h.signIn('sam@colander.test');
		let res = await h.do('PATCH', '/v1/account', { display_name: 'Sam' }, 'Cookie', cookie);
		await expectStatus(res, 403);
		expect(await errorCode(res)).toBe('csrf_required');
		await expectStatus(await h.do('POST', '/v1/auth/logout', undefined, 'Cookie', cookie), 403);
		res = await h.do('PATCH', '/v1/account', { display_name: 'Sam' }, 'Cookie', cookie, ...CSRF);
		await expectStatus(res, 200);
		await expectStatus(await h.do('POST', '/v1/auth/logout', undefined, 'Cookie', cookie, ...CSRF), 204);
		await expectStatus(await h.do('GET', '/v1/account', undefined, 'Cookie', cookie), 401);
	});

	it('sets and clears the display name, one line of at most 60 characters', async () => {
		const h = await Harness.create();
		const auth = ['Cookie', await h.signIn('sam@colander.test'), ...CSRF];
		const name = async (body: unknown) => {
			const res = await h.do('PATCH', '/v1/account', body, ...auth);
			return res.status === 200 ? ((await res.json()) as { account: { display_name: string | null } }).account.display_name : await errorCode(res);
		};
		expect(await name({ display_name: '  Sam Ortiz  ' })).toBe('Sam Ortiz');
		expect(await name({ display_name: 'ä'.repeat(60) })).toBe('ä'.repeat(60));
		expect(await name({ display_name: 'a'.repeat(61) })).toBe('invalid_display_name');
		expect(await name({ display_name: 'Sam\nOrtiz' })).toBe('invalid_display_name');
		expect(await name({ display_name: 'Sam\tOrtiz' })).toBe('invalid_display_name');
		expect(await name({ display_name: null })).toBeNull();
		expect(await h.run((store) => store.db.get('SELECT display_name FROM accounts'))).toEqual({ display_name: null });
	});

	it('ignores the product cookie on the admin host', async () => {
		const h = await Harness.create();
		const cookie = await h.signIn('maya@example.test');
		await expectStatus(await h.do('GET', '/v1/account', undefined, 'Cookie', cookie, 'x-colander-host', 'admin'), 401);
	});
});
