// Accounts and sessions (src/auth.ts and src/routes/account.ts): Go's TestMagicLinkSignIn,
// TestCSRFRequired and the reviewer token half of TestCuratorLimitsAndReviewerToken, plus the auth
// helpers against Go's net/mail and the one transaction that consumes a link and creates a session.
import { env } from 'cloudflare:workers';
import { describe, expect, it } from 'vitest';
import { hex, utf8 } from '@colander/shared/bytes';
import { Auth, csrfOk, hashInstall, hashToken, normalizeEmail, safeNext } from '../src/auth';
import { grantRole, setDisplayName } from '../src/store/accounts';
import { errorCode, expectStatus, Harness, installId } from './api';

const MINUTE = 60_000;
const sha256hex = async (s: string) => hex(new Uint8Array(await crypto.subtle.digest('SHA-256', utf8(s))));

describe('auth helpers', () => {
	it('normalizes emails exactly as Go did with net/mail', () => {
		// Generated by running Go's NormalizeEmail over these inputs.
		const vectors: [string, string | null][] = [
			['Maya@Example.test', 'maya@example.test'],
			['  sam@colander.test ', 'sam@colander.test'],
			// Go's TrimSpace: U+0085, U+00A0 and U+3000 are space, U+FEFF is not.
			['\u0085a@b.c\u3000', 'a@b.c'],
			['\u00a0a@b.c', 'a@b.c'],
			['\ufeffa@b.c', '\ufeffa@b.c'],
			['a@b', 'a@b'],
			['a.b@c.d', 'a.b@c.d'],
			['.a@b.c', null],
			['a.@b.c', null],
			['a..b@c.d', null],
			['a@b..c', null],
			['a@.b', null],
			['a@b.', null],
			['"a"@b.c', null],
			['"a b"@b.c', null],
			['Maya <maya@example.test>', null],
			['<maya@example.test>', null],
			['maya@example.test (Maya)', null],
			['maya@example.test ()', null],
			['a b@c.d', null],
			['a@b c.d', null],
			['a@[1.2.3.4]', 'a@[1.2.3.4]'],
			['a@[1.2.3.256]', null],
			['a@[01.2.3.4]', null],
			['a@[IPv6:::1]', null],
			['a@[::1]', null],
			['a@[a]', null],
			['a@', null],
			['@b.c', null],
			['', null],
			['a', null],
			['ünï@cödé.de', 'ünï@cödé.de'],
			['ÜNÏ@CÖDÉ.DE', 'ünï@cödé.de'],
			['İ@x.y', 'i@x.y'],
			['a+tag@x.y', 'a+tag@x.y'],
			["a/b=c?d^e_f`g{h|i}j~k!#$%&'*@x.y", "a/b=c?d^e_f`g{h|i}j~k!#$%&'*@x.y"],
			['a(b)@c.d', null],
			['a,b@c.d', null],
			['a;b@c.d', null],
			['a:b@c.d', null],
			['a\\b@c.d', null],
			['a@b@c.d', null],
			['a\t@b.c', null],
			['a@b.c\n', 'a@b.c'],
			['a@b-.c', 'a@b-.c'],
			['a@-b.c', 'a@-b.c'],
			['a@b_c.d', 'a@b_c.d'],
			['a@b.c.', null],
			['a@[1.2.3.4', null],
			['a@1.2.3.4]', null],
			// At most 254 bytes.
			['a'.repeat(64) + '@' + 'b'.repeat(187) + '.c', 'a'.repeat(64) + '@' + 'b'.repeat(187) + '.c'],
			['a'.repeat(64) + '@' + 'b'.repeat(188) + '.c', null]
		];
		for (const [input, want] of vectors) expect([input, normalizeEmail(input) ?? null]).toEqual([input, want]);
	});

	it('keeps the post-sign-in redirect on this site', () => {
		expect(safeNext('/review?kind=reports')).toBe('/review?kind=reports');
		for (const bad of ['', 'review', 'https://evil.example/', '//evil.example', '/\\evil.example', '/a\r\nSet-Cookie: x', '/' + 'a'.repeat(512)]) {
			expect(safeNext(bad)).toBe('/account');
		}
		expect(safeNext('/' + 'a'.repeat(511))).toBe('/' + 'a'.repeat(511));
	});

	it('hashes tokens and install IDs and refuses malformed install IDs', async () => {
		expect(hashToken('abc')).toBe(await sha256hex('abc'));
		const id = installId(1);
		expect(id).toHaveLength(22);
		expect(hashInstall(id)).toBe(await sha256hex('colander-install:' + id));
		for (const bad of [id.slice(1), id + 'A', id.slice(0, 21) + '+', id.slice(0, 20) + '==', '']) expect(hashInstall(bad)).toBeUndefined();
	});

	it('lets reads through and wants the CSRF header on writes', () => {
		const req = (method: string, headers: HeadersInit = {}) => new Request('https://getcolander.com/v1/account', { method, headers });
		for (const m of ['GET', 'HEAD', 'OPTIONS']) expect(csrfOk(req(m))).toBe(true);
		expect(csrfOk(req('POST'))).toBe(false);
		expect(csrfOk(req('PATCH', { 'X-Colander-CSRF': '0' }))).toBe(false);
		expect(csrfOk(req('PATCH', { 'X-Colander-CSRF': '1' }))).toBe(true);
	});
});

describe('email sign-in', () => {
	it('signs in through a magic link that works once and expires after 20 minutes', async () => {
		const h = await Harness.create();
		await expectStatus(await h.do('GET', '/v1/account'), 401);
		h.mail = '';
		await expectStatus(await h.do('POST', '/v1/auth/email', { email: 'Maya@Example.test', next: 'https://evil.example/' }), 202);
		const token = /token=([A-Za-z0-9_-]+)/.exec(h.mail)?.[1];
		expect(token).toBeDefined();
		expect(h.mail).toContain(`${env.PUBLIC_URL}/auth/callback?token=`);
		expect(h.mail).toContain('next=%2Faccount');

		let res = await h.do('POST', '/v1/auth/verify', { token });
		await expectStatus(res, 200);
		const cookie = res.headers.get('Set-Cookie')!;
		const value = /^colander_session=([A-Za-z0-9_-]{43});/.exec(cookie)?.[1];
		expect(value).toBeDefined();
		const expires = new Date(h.clock + 30 * 24 * 60 * MINUTE).toUTCString();
		// Dev mode: HttpOnly and SameSite=Lax, not Secure.
		expect(cookie).toBe(`colander_session=${value}; Path=/; Expires=${expires}; Max-Age=2592000; HttpOnly; SameSite=Lax`);

		res = await h.do('GET', '/v1/account', undefined, 'Cookie', `colander_session=${value}`);
		await expectStatus(res, 200);
		const { account } = (await res.json()) as { account: Record<string, unknown> };
		expect(account).toEqual({
			id: expect.stringMatching(/^acc_[a-z2-9]{16}$/),
			email: 'maya@example.test',
			display_name: null,
			role: 'member',
			plan: null,
			created_at: '2026-10-01T12:00:00Z'
		});

		// Links work once.
		res = await h.do('POST', '/v1/auth/verify', { token });
		await expectStatus(res, 400);
		expect(await errorCode(res)).toBe('link_invalid');
		// And expire after 20 minutes.
		h.mail = '';
		await h.do('POST', '/v1/auth/email', { email: 'maya@example.test' });
		const late = /token=([A-Za-z0-9_-]+)/.exec(h.mail)![1];
		h.clock += 21 * MINUTE;
		await expectStatus(await h.do('POST', '/v1/auth/verify', { token: late }), 400);
	});

	it('prints the dev mail in the block e2e/tests/stack.ts parses', async () => {
		const h = await Harness.create();
		h.mail = '';
		await h.do('POST', '/v1/auth/email', { email: 'rae@colander.test', next: '/console' });
		// stack.ts mailsSince and signInLink, applied to what the Store printed.
		const mails = h.mail
			.split('==== Colander dev mail (not sent) ====')
			.slice(1)
			.map((block) => ({
				to: /^To: (.+)$/m.exec(block)?.[1] ?? '',
				subject: /^Subject: (.+)$/m.exec(block)?.[1] ?? '',
				body: block.split('======================================')[0]!
			}));
		expect(mails).toHaveLength(1);
		expect(mails[0]!.to).toBe('rae@colander.test');
		expect(mails[0]!.subject).toBe('Your Colander sign-in link');
		const link = /^https?:\/\/\S+\/auth\/callback\?\S+$/m.exec(mails[0]!.body)?.[0];
		expect(new URL(link!).searchParams.get('next')).toBe('/console');
	});

	it('consumes the link and creates the session in one transaction', async () => {
		const h = await Harness.create();
		h.mail = '';
		await h.do('POST', '/v1/auth/email', { email: 'maya@example.test' });
		const token = /token=([A-Za-z0-9_-]+)/.exec(h.mail)![1];
		await h.run((store) => store.db.run("CREATE TRIGGER no_sessions BEFORE INSERT ON sessions BEGIN SELECT RAISE(ABORT, 'sessions are down'); END"));
		await expectStatus(await h.do('POST', '/v1/auth/verify', { token }), 500);
		// The failed session left the link unused and created no account.
		expect(
			await h.run((store) => [
				store.db.get('SELECT used_at FROM magic_links'),
				store.db.get<{ n: number }>('SELECT count(*) AS n FROM accounts')!.n
			])
		).toEqual([{ used_at: null }, 0]);
		await h.run((store) => store.db.run('DROP TRIGGER no_sessions'));
		await expectStatus(await h.do('POST', '/v1/auth/verify', { token }), 200);
	});

	it('limits links to 5 per email and 30 per address an hour, writing nothing when refused', async () => {
		const h = await Harness.create();
		for (let i = 0; i < 5; i++) await expectStatus(await h.do('POST', '/v1/auth/email', { email: 'maya@example.test' }), 202);
		let res = await h.do('POST', '/v1/auth/email', { email: 'MAYA@example.test' });
		await expectStatus(res, 429);
		expect(await errorCode(res)).toBe('rate_limited');
		expect(res.headers.get('Retry-After')).toBe('720');
		expect(await h.run((store) => store.db.get<{ n: number }>('SELECT count(*) AS n FROM magic_links')!.n)).toBe(5);
		// 12 minutes refill one link.
		h.clock += 12 * MINUTE;
		await expectStatus(await h.do('POST', '/v1/auth/email', { email: 'maya@example.test' }), 202);

		// The address quota counts every email; another address has its own.
		for (let i = 0; i < 29; i++) await expectStatus(await h.do('POST', '/v1/auth/email', { email: `user${i}@example.test` }), 202);
		await expectStatus(await h.do('POST', '/v1/auth/email', { email: 'user99@example.test' }), 429);
		await expectStatus(await h.do('POST', '/v1/auth/email', { email: 'user99@example.test' }, 'x-colander-ip-hash', 'elsewhere'), 202);
	});

	it('refuses bad bodies as Go decode() did', async () => {
		const h = await Harness.create();
		const cases: [unknown, number, string][] = [
			[{ email: 'not an email' }, 400, 'invalid_email'],
			[{ email: 'maya@example.test', remember: true }, 400, 'unknown_field'],
			[{ email: 5 }, 400, 'invalid_json'],
			['{"email": "maya@example.test"} {}', 400, 'invalid_json'],
			['', 400, 'invalid_json'],
			['[]', 400, 'invalid_json'],
			[{ email: 'maya@example.test', next: 'x'.repeat(5000) }, 413, 'too_large']
		];
		for (const [body, status, code] of cases) {
			const res = await h.do('POST', '/v1/auth/email', body);
			await expectStatus(res, status);
			expect(await errorCode(res)).toBe(code);
		}
		const res = await h.do('POST', '/v1/auth/email', { email: 'maya@example.test', remember: true });
		expect(((await res.json()) as { error: { message: string } }).error.message).toBe('The request has a field this API does not accept: "remember".');
		// Go matches field names regardless of case, and null keeps the zero value.
		await expectStatus(await h.do('POST', '/v1/auth/email', { Email: 'maya@example.test', next: null }), 202);
	});

	it('logs out, clearing the session and the cookie, and sets Secure outside dev', async () => {
		const h = await Harness.create();
		const cookie = await h.signIn('maya@example.test');
		const res = await h.do('POST', '/v1/auth/logout', undefined, 'Cookie', cookie, 'X-Colander-CSRF', '1');
		await expectStatus(res, 204);
		expect(res.headers.get('Set-Cookie')).toBe('colander_session=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax');
		await expectStatus(await h.do('GET', '/v1/account', undefined, 'Cookie', cookie), 401);
		expect(await h.run((store) => store.db.get<{ n: number }>('SELECT count(*) AS n FROM sessions')!.n)).toBe(0);

		const cleared = await h.run((store) => new Auth(store.db, () => h.clock, false).signOut(new Request('https://getcolander.com/')));
		expect(cleared).toBe('colander_session=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Lax');
	});
});

describe('account', () => {
	it('needs the CSRF header on cookie writes', async () => {
		const h = await Harness.create();
		const cookie = await h.signIn('sam@colander.test');
		let res = await h.do('PATCH', '/v1/account', { display_name: 'Sam' }, 'Cookie', cookie);
		await expectStatus(res, 403);
		expect(await errorCode(res)).toBe('csrf_required');
		await expectStatus(await h.do('POST', '/v1/auth/logout', undefined, 'Cookie', cookie), 403);
		res = await h.do('PATCH', '/v1/account', { display_name: 'Sam' }, 'Cookie', cookie, 'X-Colander-CSRF', '1');
		await expectStatus(res, 200);
		await expectStatus(await h.do('POST', '/v1/auth/logout', undefined, 'Cookie', cookie, 'X-Colander-CSRF', '1'), 204);
		await expectStatus(await h.do('GET', '/v1/account', undefined, 'Cookie', cookie), 401);
	});

	it('sets and clears the display name, one line of at most 60 characters', async () => {
		const h = await Harness.create();
		const auth = ['Cookie', await h.signIn('sam@colander.test'), 'X-Colander-CSRF', '1'];
		const name = async (body: unknown) => {
			const res = await h.do('PATCH', '/v1/account', body, ...auth);
			return res.status === 200 ? ((await res.json()) as { account: { display_name: string | null } }).account.display_name : await errorCode(res);
		};
		expect(await name({ display_name: '  Sam Ortiz  ' })).toBe('Sam Ortiz');
		expect(await name({ display_name: 'ä'.repeat(60) })).toBe('ä'.repeat(60));
		expect(await name({ display_name: 'a'.repeat(61) })).toBe('invalid_display_name');
		expect(await name({ display_name: 'Sam\nOrtiz' })).toBe('invalid_display_name');
		expect(await name({ display_name: 'Sam\tOrtiz' })).toBe('invalid_display_name');
		expect(await name({ display_name: null })).toBeNull();
		expect(await h.run((store) => store.db.get('SELECT display_name FROM accounts'))).toEqual({ display_name: null });
	});

	it('gives curators and staff a reviewer token that replaces the earlier one', async () => {
		const h = await Harness.create();
		const member = await h.signIn('maya@example.test');
		let res = await h.do('POST', '/v1/account/reviewer-token', undefined, 'Cookie', member, 'X-Colander-CSRF', '1');
		await expectStatus(res, 403);
		expect(await errorCode(res)).toBe('forbidden');

		await h.run((store) => {
			const a = grantRole(store.db, 'sam@colander.test', 'curator', h.s);
			setDisplayName(store.db, a.id, 'Sam');
		});
		const curator = await h.signIn('sam@colander.test');
		const issue = async () => {
			const r = await h.do('POST', '/v1/account/reviewer-token', undefined, 'Cookie', curator, 'X-Colander-CSRF', '1');
			await expectStatus(r, 200);
			return ((await r.json()) as { token: string }).token;
		};
		const first = await issue();
		expect(await h.run((store) => store.auth.reviewerAccount(first)?.email)).toBe('sam@colander.test');
		const second = await issue();
		expect(await h.run((store) => [store.auth.reviewerAccount(first), store.auth.reviewerAccount(second)?.displayName])).toEqual([undefined, 'Sam']);
		// Only the hash is stored.
		expect(await h.run((store) => store.db.get('SELECT token_hash FROM reviewer_tokens'))).toEqual({ token_hash: hashToken(second) });
	});
});
