// Writes src/inpage/tokens.generated.ts from src/styles/colander.css and src/styles/parts.css,
// so the in-page shadow DOM uses exactly the tokens and component CSS the pages use.
//
//   node scripts/gen-inpage-tokens.ts           write the file
//   node scripts/gen-inpage-tokens.ts --check   fail when the committed file is stale
//
// Runs in WXT's prepare hook and in the web prebuild. A vitest test runs it in memory too.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const PATHS = {
	tokens: resolve(ROOT, 'src/styles/colander.css'),
	parts: resolve(ROOT, 'src/styles/parts.css'),
	out: resolve(ROOT, 'src/inpage/tokens.generated.ts')
};

type Rule = { prelude: string; body: string };

/** Top-level rules of a stylesheet, comments removed. Bodies of at-rules stay raw. */
export function rules(css: string): Rule[] {
	const src = css.replace(/\/\*[\s\S]*?\*\//g, '');
	const out: Rule[] = [];
	let start = 0;
	for (let i = 0; i < src.length; i++) {
		const c = src[i];
		if (c === ';') start = i + 1;
		else if (c === '{') {
			let depth = 1;
			let j = i + 1;
			for (; j < src.length && depth; j++) {
				if (src[j] === '{') depth++;
				else if (src[j] === '}') depth--;
			}
			out.push({ prelude: src.slice(start, i).trim(), body: src.slice(i + 1, j - 1) });
			i = j - 1;
			start = j;
		}
	}
	return out;
}

/** Custom property declarations of one rule body, in source order, whitespace collapsed. */
export function declarations(body: string): [string, string][] {
	const out: [string, string][] = [];
	for (const raw of body.split(/;(?![^(]*\))/)) {
		const d = raw.trim();
		if (!d.startsWith('--')) continue;
		const k = d.indexOf(':');
		out.push([d.slice(0, k).trim(), d.slice(k + 1).replace(/\s+/g, ' ').trim()]);
	}
	return out;
}

/** The light :root block and the dark block of colander.css. */
export function tokenBlocks(css: string): { light: [string, string][]; dark: [string, string][] } {
	const top = rules(css);
	const light = top.find((r) => r.prelude === ':root');
	const media = top.find((r) => /^@media\s*\(prefers-color-scheme:\s*dark\)$/.test(r.prelude));
	const dark = media && rules(media.body).find((r) => r.prelude === ":root:not([data-theme='light'])");
	if (!light || !dark) throw new Error('colander.css needs a :root block and a prefers-color-scheme: dark block');
	return { light: declarations(light.body), dark: declarations(dark.body) };
}

/** Comments and needless whitespace removed. Good enough for our own hand-written CSS. */
export function minify(css: string): string {
	return css
		.replace(/\/\*[\s\S]*?\*\//g, '')
		.replace(/\s+/g, ' ')
		.replace(/\s*([{};,>])\s*/g, '$1')
		.replace(/:\s+/g, ':')
		.replace(/;}/g, '}')
		.trim();
}

/** Page-only tokens stay out of host pages, which keeps SHEET small. */
export const PAGE_ONLY = /^--cl-(paper|wash|mark|band|band-card|font|display.*|title-lg|lead|stat.*|eyebrow|figure|s(7|8|9|10))$/;

const decls = (d: [string, string][]) =>
	d
		.filter(([k]) => !PAGE_ONLY.test(k))
		.map(([k, v]) => `${k}:${v}`)
		.join(';');

export function generate(tokensCss: string, partsCss: string): string {
	const { light, dark } = tokenBlocks(tokensCss);
	return `// Generated by scripts/gen-inpage-tokens.ts from src/styles/colander.css and parts.css.
// Do not edit. Run \`pnpm -C packages/shared gen:tokens\` after changing either file.

/** The light tokens, for every in-page host. */
export const TOKENS_LIGHT = ${JSON.stringify(decls(light))};

/** The dark tokens, for hosts on dark pages. */
export const TOKENS_DARK = ${JSON.stringify(decls(dark))};

/** The :host and :host([theme='dark']) blocks. */
export const TOKENS = \`:host{\${TOKENS_LIGHT}}:host([theme='dark']){\${TOKENS_DARK}}\`;

/** Component CSS shared with pages: chip, buttons, links, popover, evidence card, toast. */
export const PARTS = ${JSON.stringify(minify(partsCss))};
`;
}

function main() {
	const next = generate(readFileSync(PATHS.tokens, 'utf8'), readFileSync(PATHS.parts, 'utf8'));
	if (process.argv.includes('--check')) {
		if (readFileSync(PATHS.out, 'utf8') !== next) {
			console.error('src/inpage/tokens.generated.ts is stale. Run pnpm -C packages/shared gen:tokens.');
			process.exit(1);
		}
		return;
	}
	writeFileSync(PATHS.out, next);
	console.log('Wrote src/inpage/tokens.generated.ts');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
